### ISSUE TITLE
i keep getting JsonParseErr for the same strings

### ISSUE THREAD

**Issue by pawarherschel** [Deepp0925/lingual#3]
can i get your discord so we can communicate further?

**Comment by Deepp0925** [comment]
@deeppatel2771

**Comment by pawarherschel** [comment]
sent request. my discord username is `Kat Sakura`

**Comment by Deepp0925** [comment]
Fixed in [dc4892f](https://github.com/Deepp0925/lingual/commit/dc4892f943cd4be235422c92dd76db5933459b30)
